describe('TAB navigation', () => {
  beforeEach(() => {
    cy.setCookie('cookieConsent', 'accepted')
    cy.visit('/')
    cy.get('[aria-label="Open messenger"]').click()
  })

  it('navigates through the messenger using the TAB key', () => {
    cy.get('#messenger-name')
      .should('be.focused')
      .type('John Doe')
    cy.pressTAB()
    cy.get('#email')
      .should('be.focused')
      .type('johndoe@example.com')
    cy.pressTAB()
    cy.get('#message')
      .should('be.focused')
      .type('The client with ID 5 has no contact info available')
    cy.pressTAB()
    cy.contains('button', 'Send')
      .should('be.focused')
      .click()
    cy.contains('Your message has been sent.').should('be.visible')
    cy.pressTAB()
    cy.get('[aria-label="Close messenger"')
      .should('be.focused')
      .click()
    cy.get('[aria-label="Open messenger"]').should('be.visible')
  })
})